import re

''''>NP_188809.2 isocitrate lyase [Arabidopsis thaliana]
Consensus pattern:
K-[KR]-C-G-H-[LMQR]'''

seq = 'MAASFSVPSMIMEEEGRFEAEVAEVQTWWSSERFKLTRRPYTARDVVALRGHLKQGYASNEMAKKLWRTLKSHQANGTASRTFGALDPVQVTMMAKHLDTIYVSGWQCSSTHTSTNEPGPDLADYPYDTVPNKVEHLFFAQQYHDRKQREARMSMSREERTKTPFVDYLKPIIADGDTGFGGTTATVKLCKLFVERGAAGVHIEDQSSVTKKCGHMAGKVLVAVSEHINRLVAARLQFDVMGTETVLVARTDAVAATLIQSNIDARDHQFILGATNPSLRGKSLSSLLAEGMTVGKNGPALQSIEDQWLGSAGLMTFSEAVVQAIKRMNLNENEKNQRLSEWLTHARYENCLSNEQGRVLAAKLGVTDLFWDWDLPRTREGFYRFQGSVAAAVVRGWAFAQIADIIWMETASPDLNECTQFAEGIKSKTPEVMLAYNLSPSFNWDASGMTDQQMVEFIPRIARLGYCWQFITLAGFHADALVVDTFAKDYARRGMLAYVERIQREERTHGVDTLAHQKWSGANYYDRYLKTVQGGISSTAAMGKGVTEEQFKESWTRPGADGMGEGTSLVVAKSRM'

s = re.search(r"K[K,R]CGH[L,M,Q,R]", seq)
n = str(s.start())
s = s.group()


print('Isocitrate lyase (FNP_188809.2) contains its active site '+s+' starting from '+n+' position')
